"""Pure domain types and algebras. No I/O, no LLM, no framework."""

from assist.domain.catalog import Candidate, Person, Pick, Title
from assist.domain.constraints import (
    AddOp,
    ClearOp,
    ConstraintDelta,
    ConstraintState,
    FieldOp,
    RemoveOp,
    ReplaceOp,
    SetOp,
    merge,
)
from assist.domain.context import ServerUserCtx
from assist.domain.enums import (
    Audience,
    CreditRole,
    DegradedReason,
    DeltaSource,
    DeviceClass,
    GenreId,
    MaturityRating,
    MediaType,
    MoodId,
    Pace,
    Package,
    RecencyBias,
    Route,
    SpeechAct,
    is_stricter_than,
    maturity_rank,
)
from assist.domain.picks import min_picks_for, sanitize_picks

__all__ = [
    "AddOp",
    "Audience",
    "Candidate",
    "ClearOp",
    "ConstraintDelta",
    "ConstraintState",
    "CreditRole",
    "DegradedReason",
    "DeltaSource",
    "DeviceClass",
    "FieldOp",
    "GenreId",
    "MaturityRating",
    "MediaType",
    "MoodId",
    "Pace",
    "Package",
    "Person",
    "Pick",
    "RecencyBias",
    "RemoveOp",
    "ReplaceOp",
    "Route",
    "ServerUserCtx",
    "SetOp",
    "SpeechAct",
    "Title",
    "is_stricter_than",
    "maturity_rank",
    "merge",
    "min_picks_for",
    "sanitize_picks",
]
