graph TD;
	__start__ --> load_session;
	broaden_constraints --> retrieve;
	guard -.-> intent;
	guard -. &nbsp;refusal&nbsp; .-> reply_refusal;
	intent --> merge_constraints;
	load_session --> guard;
	merge_constraints -.-> resolve_people;
	merge_constraints -.-> retrieve;
	mint_chips --> persist;
	rank --> validate_availability;
	reply_clarify --> sanitize_picks;
	reply_generative --> sanitize_picks;
	reply_refusal --> sanitize_picks;
	reply_template --> sanitize_picks;
	resolve_people --> retrieve;
	retrieve -. &nbsp;broaden&nbsp; .-> broaden_constraints;
	retrieve -.-> rank;
	sanitize_picks --> mint_chips;
	validate_availability -. &nbsp;clarify&nbsp; .-> reply_clarify;
	validate_availability -. &nbsp;generative&nbsp; .-> reply_generative;
	validate_availability -. &nbsp;refusal&nbsp; .-> reply_refusal;
	validate_availability -. &nbsp;template&nbsp; .-> reply_template;
	persist --> __end__;
